tasks_manage/tasks/urls.py
from django.urls import path

from .views import TaskView, TaskAllView, TaskFileView, TaskFormCreateView, TaskDeleteView

app_name = 'tasks'

urlpatterns = [
    path('create/', TaskFormCreateView.as_view(), name='tasks_create'),
    # path('create/', TaskCreate.as_view()),
    path('<task_id>/file', TaskFileView.as_view(), name='TaskFileView'),
    path('<task_id>/del/', TaskDeleteView.as_view(), name='TaskDeleteView'),
    path('<task_id>/', TaskView.as_view(), name='TaskView'),
    path('', TaskAllView.as_view(), name='TaskAllView')
]

tasks_manage/tasks_manage/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("tasks/", include("tasks.urls"), name='tasks'),
]

tasks_manage/users/urls.py
from django.urls import path

from .views import UsersProfileView

urlpatterns = [
    path('<user_id>/profile', UsersProfileView.as_view()),
]

tasks_manage/file/models.py
from django.db import models

# Create your models here.

tasks_manage/login/models.py
from django.db import models

# Create your models here.

tasks_manage/register/models.py
from django.db import models

# Create your models here.

tasks_manage/tasks/models.py
from django.db import models

STATUS = [('Запланирована ', 'Запланирована'), ('В работе', 'В работе'),
          ('Выполнена', 'Выполнена'), ('Отменена', 'Отменена')]


class Tasks(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=255)
    file = models.FileField(upload_to='documents/')
    status = models.CharField(max_length=17, choices=STATUS, default='Запланирована')
    date_of_create = models.DateTimeField()
    deadline = models.DateField()

tasks_manage/users/models.py
from django.db import models
from tasks.models import Tasks


STATUS = [('Обычный', 'Обычный'), ('Премиум', 'Премиум')]

class Profiles(models.Model):
    phone = models.CharField(max_length=15)
    # status = models.CharField(max_length=7)
    status = models.CharField(max_length=7, choices=STATUS, default='Обычный')
    avatar = models.CharField(max_length=255)
    profile = models.TextField(max_length=255)


class Users(models.Model):
    name = models.CharField(max_length=35, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=20)
    fk_user_profile = models.OneToOneField(Profiles, unique=True, on_delete=models.CASCADE)


class UsersTasks(models.Model):
    user_id = models.ForeignKey(Users, on_delete=models.CASCADE)
    task_id = models.ForeignKey(Tasks, on_delete=models.CASCADE)

tasks_manage/tasks/forms.py
from django.forms import ModelForm
from .models import Tasks


class TaskForm(ModelForm):

    class Meta:
        model = Tasks
        fields = ['name', 'description', 'status', 'file', 'date_of_create', 'deadline']

tasks_manage/file/views.py
from django.shortcuts import render

# Create your views here.

tasks_manage/login/views.py
from django.shortcuts import render

# Create your views here.

tasks_manage/register/views.py
from django.shortcuts import render

# Create your views here.

tasks_manage/tasks/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DeleteView

from .forms import TaskForm
from .models import Tasks


# class TaskCreate(CreateView):
    # model = Tasks
    # fields = ['name', 'description']
    # success_url = reverse_lazy('tasks')
    # template_name = 'tasks/create2.html'
    # form_class = TaskForm

class TaskFormCreateView(View):
    def get(self, request,  *args, **kwargs):
        form = TaskForm()
        return render(request, 'tasks/create2.html',
                      {'form': form})

    def post(self, request, *args, **kwargs):
        form = TaskForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('TaskAllView')
        return render(request, 'tasks/create2.html', {'form': form})


class TaskDeleteView(View):
    def get(self, request,  *args, **kwargs):
        task_id = kwargs.get('task_id')
        # task = Tasks.objects.get(pk=task_id)
        return render(request, 'tasks/task_del.html', context={
            'task_id': task_id,
        })

    def delete(self, request, *args, **kwargs):
        task_id = kwargs.get('task_id')
        task = Tasks.objects.get(pk=task_id)
        if task:
            task.delete()
        return redirect('tasks:TaskAllView')


class TaskView(View):
    def get(self, request, *args, **kwargs):
        tasks_id = kwargs.get('task_id')
        task = Tasks.objects.get(pk=tasks_id)
        return render(request, 'tasks/show.html', context={
            'task': task,
        })


class TaskAllView(View):
    def get(self, request, *args, **kwargs):
        tasks = Tasks.objects.all()[:35]
        return render(request, 'tasks/show_all.html', context={
            'tasks': tasks,
        })


class TaskFileView(View):
    def get(self, request, *args, **kwargs):
        tasks_id = kwargs.get('task_id')
        task = Tasks.objects.get(pk=tasks_id)
        return render(request, 'tasks/show_file.html', context={
            'task': task,
        })


class TaskDelete(DeleteView):
    model = Tasks
    success_url = reverse_lazy('TaskDelete')

tasks_manage/users/views.py
from django.shortcuts import render
from django.views import View
from .models import Users, Profiles


class UsersProfileView(View):
    def get(self, request, *args, **kwargs):
        user_id = kwargs.get('user_id')
        user = Users.objects.get(pk=user_id)
        profile = Profiles.objects.get(pk=user_id)
        return render(request, 'users/show.html', context={
            'user': user, 'profile': profile
        })

tasks_manage/templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
		<title>Example</title>
		<meta charset="utf-8" />
		<link rel="icon" href="{% static "images/logo.svg" %}" >
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static "assets/css/main.css"%}" />	
		<noscript><link rel="stylesheet" href="{% static "assets/css/noscript.css"%}" /></noscript>
		{% block css %}
		{% endblock %}
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">
				<!-- Header -->

				<!-- Main -->
					<div id="main">
						<div class="inner">
                            {% block content %}

                            {% endblock %}
							<!-- Paginator -->
							{% if page_obj %}<div style="text-align: center;"><hr>{% include 'includes/paginator.html' %}</div>{% endif %}
						</div>
					</div>
				<!-- Footer -->

			</div>
		<!-- Scripts -->
			<script src={% static "assets/js/jquery.min.js"%}></script>
			<script src={% static "assets/js/browser.min.js"%}></script>
			<script src={% static "assets/js/breakpoints.min.js"%}></script>
			<script src={% static "assets/js/util.js"%}></script>
			<script src={% static "assets/js/main.js"%}></script>
			{% block js %}
			{% endblock %}
	</body>
</html>

tasks_manage/templates/tasks/create2.html
    <h1>Создать задачу</h1>
    <form action="{% url 'tasks:tasks_create' %}" method="post"
        enctype="multipart/form-data">
        {% csrf_token %}
        <table border="1">
        {{ form }}
        </table>
        <input type="submit" value="Создать">
    </form>

tasks_manage/templates/tasks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <form action="{% url 'tasks' %}" method="post">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

tasks_manage/templates/tasks/show.html
    <h1>Задача </h1>

        <h2>Название задачи: {{ task.name }}</h2>
        <div>Описание задачи: {{ task.description }}</div>
        <div>Статус: {{ task.status }}</div>
        <div>Дата и время создания задачи: {{ task.date_of_create }}</div>
        <div>Дедлайн: {{ task.deadline }}</div>

tasks_manage/templates/tasks/show_all.html
    <h1>Список задач </h1>
        {% for task in tasks %}
            <h2>Название задачи: {{ task.name }}</h2>
            <div>Описание задачи: {{ task.description }}</div>
            <div>Статус: {{ task.status }}</div>
            <div>Дата и время создания задачи: {{ task.date_of_create }}</div>
            <div>Дедлайн: {{ task.deadline }}</div>
        {% endfor %}

tasks_manage/templates/tasks/show_file.html
    <h1>Файл прилагаемый к задаче: {{ task.name }}</h1>
        <h2>Содержимое файла: {{ task.file }}</h2>

tasks_manage/templates/tasks/task_del.html
    <h1>Удалить задачу: {{ task_id }}</h1>
    <form action="{% url 'tasks:TaskDeleteView' task_id=task_id %}" method="delete">

    </form>

tasks_manage/templates/users/show.html
    <h1>Профиль пользователя </h1>

        <h2>Имя пользователя: {{ user.name }}</h2>
        <div>Электронный адрес: {{ user.email|slice:":200" }}</div>
        <div>Телефон: {{ profile.phone }}</div>
        <div>Статус: {{ profile.status }}</div>
        <div>Адрес аватара: {{ profile.avatar }}</div>
        <div>Данные профиля: {{ profile.profile }}</div>